MontCrest_Task_ClietSide/Models/Model.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MontCrest_Task_ClietSide.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MontCrestEntities : DbContext
    {
        public MontCrestEntities()
            : base("name=MontCrestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StudentRegistration> StudentRegistrations { get; set; }
    }
}

MontCrest_Task_ClietSide/Models/Model.Designer.cs
// T4 code generation is enabled for model 'C:\Users\PRASAD\Desktop\MontCrest_Task_ClietSide\Models\Model.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

MontCrest_Task_ClietSide/Models/Model.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

MontCrest_Task_ClietSide/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MontCrest_Task_ClietSide.Models
{
    public class Student
    {
        public int sid { get; set; }
        [Required(ErrorMessage = "Please Enter First Name")]
        [MinLength(3, ErrorMessage = "Minimum 3 Charecters Required")]
        public string Fname { get; set; }
        [Required(ErrorMessage = "Please Enter Last Name")]
        [MinLength(3, ErrorMessage = "Minimum 3 Charecters Required")]
        public string Lname { get; set; }
        [Required(ErrorMessage = "Please Enter Email")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please Enter Password")]
        [RegularExpression("^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$",ErrorMessage = "Minimum eight characters, at least one letter and one number")]

        public string Password { get; set; }
        [Required(ErrorMessage = "Please Enter Mobile Number")]
        [RegularExpression("[0-9]{10}", ErrorMessage = "Enter 10 Digit Number")]
        public string Mobile { get; set; }
        [Required(ErrorMessage = "Please Enter Address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please Enter Adhar No")]
        [RegularExpression("[0-9]{12}", ErrorMessage = "Enter 12 Digit Number")]
        public string Adharno { get; set; }
        public string Profile { get; set; }
        public string Role { get; set; }
    }
}

MontCrest_Task_ClietSide/Models/StudentRegistration.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MontCrest_Task_ClietSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRegistration
    {
        public int sid { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Adharno { get; set; }
        public string Profile { get; set; }
        public string Role { get; set; }
    }
}

MontCrest_Task_ClietSide/Controllers/DashBoardController.cs
using Microsoft.Ajax.Utilities;
using MontCrest_Task_ClietSide.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MontCrest_Task_ClietSide.Controllers
{
    public class DashBoardController : Controller
    {
        MontCrestEntities db;
        public DashBoardController()
        {
            db= new MontCrestEntities();
        }
        // GET: DashBoard
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SIndex(string email)
        {
            StudentRegistration s=db.StudentRegistrations.FirstOrDefault(e=>e.Email==email);
            if (s.Role == "admin")
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(s);
            }
        }
        public ActionResult Create()
        {
            ViewBag.msg = "";
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Student s,HttpPostedFileBase photo)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else if (photo==null)
            {
                ViewBag.msg = "Please Select Photo";
                return View();
            }
            else
            {
                StudentRegistration sr=new StudentRegistration()
                {
                    Fname=s.Fname,
                    Lname=s.Lname,
                    Email=s.Email,
                    Password=s.Password,
                    Mobile=s.Mobile,
                    Address=s.Address,
                    Adharno=s.Adharno,
                    Role=s.Role
                };
                if (photo.ContentLength > 0)
                {
                    string imgname = s.Fname + Path.GetExtension(photo.FileName);
                    string imgpath = Server.MapPath("~/Profilephotos/" + imgname);
                    sr.Profile = imgname;
                    photo.SaveAs(imgpath);
                    db.StudentRegistrations.Add(sr);
                    db.SaveChanges();
                    return RedirectToAction("Index","Login");
                }
                return View();
            }
        }
        public ActionResult Logout()
        {
            return View();
        }
    }
}

MontCrest_Task_ClietSide/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MontCrest_Task_ClietSide.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MontCrest_Task_ClietSide/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MontCrest_Task_ClietSide.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
    }
}

MontCrest_Task_ClietSide/Views/DashBoard/Create.cshtml
@model MontCrest_Task_ClietSide.Models.Student
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script>

    </script>
</head>
<body>
    <form action="Create" method="post" enctype="multipart/form-data">
        @Html.AntiForgeryToken()
        <table>
            <tr>
                <td>First Name</td>
                <td>@Html.TextBoxFor(e => e.Fname)</td>
                <td style="color:red">@Html.ValidationMessageFor(e => e.Fname)</td>
            </tr>
            <tr>
                <td>Last Name</td>
                <td>@Html.TextBoxFor(e => e.Lname)</td>
                <td style="color:red">@Html.ValidationMessageFor(e => e.Lname)</td>
            </tr>
            <tr>
                <td>Email Address</td>
                <td>@Html.TextBoxFor(e => e.Email)</td>
                <td style="color:red">@Html.ValidationMessageFor(e => e.Email)</td>
            </tr>
            <tr>
                <td>Password</td>
                <td>@Html.PasswordFor(e => e.Password)</td>
                <td style="color:red">@Html.ValidationMessageFor(e => e.Password)</td>
            </tr>
            <tr>
                <td>Mobile Number</td>
                <td>@Html.TextBoxFor(e => e.Mobile)</td>
                <td style="color:red">@Html.ValidationMessageFor(e => e.Mobile)</td>
            </tr>
            <tr>
                <td>Address</td>
                <td>@Html.TextAreaFor(e => e.Address)</td>
                <td style="color:red">@Html.ValidationMessageFor(e => e.Address)</td>
            </tr>
            <tr>
                <td>Adhar No</td>
                <td>@Html.TextBoxFor(e => e.Adharno)</td>
                <td style="color:red">@Html.ValidationMessageFor(e => e.Adharno)</td>
            </tr>
            <tr>
                <td>Profile Photo</td>
                <td><input type="file" name="photo" /></td>
                <td><h3 style="color:red">@ViewBag.msg</h3></td>
            </tr>
            <tr>
                <td><input type="submit" value="SUBMIT" /></td>
                <td><input type="button" value="Login" onclick="window.location.href='@Url.Action("Index","Login")'" /></td>
            </tr>
        </table>
    </form>
</body>
</html>

MontCrest_Task_ClietSide/Views/DashBoard/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DashBoard Index</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script>
        var token = "";
        if (localStorage.getItem("token") == null) {
            window.location.href = "/Login/Index";
        }
        else {
            token = localStorage.getItem("token");
        }
        $(document).ready(function () {
            GetStudents();
        })
        function GetStudents() {
            $.ajax({
                url: 'https://localhost:44385/api/students',
                method: 'get',
                headers: {
                    "Authorization": "Bearer " + token,
                    'content-type': 'application/json'
                },
                success: function (resp) {
                    $.each(resp, function (i, d) {
                        $("#tbldata").append("<tr><td>"
                            + d.sid + "</td><td>"
                            + d.Fname + "</td><td>"
                            + d.Lname + "</td><td>"
                            + d.Email + "</td><td>"
                            + d.Password + "</td><td>"
                            + d.Mobile + "</td><td>"
                            + d.Address + "</td><td>"
                            + d.Adharno + "</td><td><img src='../Profilephotos/"
                            + d.Profile + "' height='100px' width='100px' /></td><td>"
                            + '<input type="button" value="Delete" onclick="Delete(' + d.sid + ')"/>'
                            + "</td></tr>")
                    })
                }
            })
        }
        function Delete(id) {
            ajax({
                url: 'https://localhost:44385/api/student'+id,
                method: 'Delete',
                success: function (res) {
                    alert(res);
                }

            })
        }
    </script>
</head>
<body>
    
    <div>
        <h2 style="text-align:center">Welcome To Admin Profile</h2>
        <input style="margin-left:45%" type="button" class="btn btn-danger" value="LOG OUT" onclick="window.location.href='@Url.Action("Logout","DashBoard")'" /><br /><br />
        <table class="table table-bordered text-center">
            <thead>
                <tr>
                    <th>Student Id</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Password</th>
                    <th>Mobile</th>
                    <th>Address</th>
                    <th>Adhar No</th>
                    <th>Photo</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="tbldata"></tbody>
        </table>
    </div>
</body>
</html>

MontCrest_Task_ClietSide/Views/DashBoard/Logout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Logout</title>
    <script>
        localStorage.removeItem("token");
        window.location.href = "/Login/Index";
    </script>
</head>
<body>
    <div> 
    </div>
</body>
</html>

MontCrest_Task_ClietSide/Views/DashBoard/SIndex.cshtml
@model MontCrest_Task_ClietSide.Models.StudentRegistration
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SIndex</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="row">
        <div class="col-md-9 text-center">
            <h1 style="text-align:center">Welcome To Student Profile</h1><br />
            <input type="button" class="btn btn-danger" value="LOG OUT" onclick="window.location.href='@Url.Action("Logout","DashBoard")'" />
        </div>
        <div class="col-md-3">
            <img src="../Profilephotos/@Model.Profile" height="200px" width="200px" />
        </div>
    </div><hr />
    <table class="table table-bordered text-center">
        <thead>
            <tr>
                <th>Student Name</th>
                <td>@Model.Fname @Model.Lname</td>
            </tr>
            <tr>
                <th>Email Address</th>
                <td>@Model.Email</td>
            </tr>
            <tr>
                <th>Mobile Number</th>
                <td>@Model.Mobile</td>
            </tr>
            <tr>
                <th>Adhar Number</th>
                <td>@Model.Adharno</td>
            </tr>
        </thead>
    </table>
</body>
</html>

MontCrest_Task_ClietSide/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

MontCrest_Task_ClietSide/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

MontCrest_Task_ClietSide/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

MontCrest_Task_ClietSide/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#btnlogin").click(function () { Checklogin(); });
        })
        function Checklogin()
        {
            var email = $("#email").val();
            var pass = $("#pass").val();
            var url = '@Url.Action("SIndex", "DashBoard")' + '?email=' + encodeURIComponent(email);
            var st = "username=" + email + "&password=" + pass + "&grant_type=password";
            $.ajax({
                url: 'https://localhost:44385/token',
                method: 'post',
                data: st,
                success: function (resp) {
                    localStorage.setItem("token", resp.access_token);
                    window.location.href = url;

        },
                error: function (err) {
                    $("#msg").html("Invalid Employee or Password");
        }
            })
        }
    </script>
</head>
<body>
    <div>
        <table>
            <tr>
                <td>User Email</td>
                <td><input type="text" id="email" /></td>
            </tr>
            <tr>
                <td>User Password</td>
                <td><input type="password" id="pass" /></td>
            </tr>
            <tr>
                <td><input type="button" id="btnlogin" value="Login" /></td>
                <td><input type="button" id="btnlogin" value="Register" onclick="window.location.href='@Url.Action("Create","DashBoard")'" /></td>
            </tr>
        </table>
        <h2 id="msg" style="color:red"></h2>
    </div>
</body>
</html>

MontCrest_Task_ClietSide/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>